import random

# Table 3-160: Liquid Potions
LIQUID_POTIONS = [
    {"die": "01-10", "color": "Black", "consistency": "Chunky", "smell": "Alcohol", "other": "Bubbles or effervesces"},
    {"die": "11-20", "color": "Blue", "consistency": "Contains sediment or precipitates", "smell": "Burned Toast", "other": "Clouded"},
    {"die": "21-30", "color": "Brown", "consistency": "Multiple viscosities (layered or floating blobs)", "smell": "Dung or manure", "other": "Colored flecks within"},
    {"die": "31-40", "color": "Clear", "consistency": "Oily", "smell": "Flowers", "other": "Fumes, seethes, or sublimates in air"},
    {"die": "41-50", "color": "Green", "consistency": "Sludge", "smell": "Newly-mown grass", "other": "Layered colors"},
    {"die": "51-60", "color": "Grey", "consistency": "Syrupy", "smell": "No smell", "other": "Opalescent (swirls of color change with light)"},
    {"die": "61-70", "color": "Orange", "consistency": "Syrupy", "smell": "Rot", "other": "Phosphorescent (glows)"},
    {"die": "71-80", "color": "Purple", "consistency": "Viscous", "smell": "Smoke", "other": "Reflective or metallic"},
    {"die": "81-90", "color": "Red", "consistency": "Watery", "smell": "Vinegar", "other": "Swirls of color (actual color, not just opalescent)"},
    {"die": "91-00", "color": "White", "consistency": "Watery", "smell": "Wet dog", "other": "Translucent"},
]

# Table 3-161: Powdered Potions
POWDERED_POTIONS = [
    {"die": "01-10", "color": "Black", "smell": "Burned Toast", "other": "Gives off wisps of steam or sublimation"},
    {"die": "11-20", "color": "Blue", "smell": "Dung or manure", "other": "Is compressed into a block, chalk-like stick, tablet, capsule, or sphere"},
    {"die": "21-30", "color": "Brown", "smell": "Flowers", "other": "Large Grains (like black powder)"},
    {"die": "31-40", "color": "Clear", "smell": "Gunpowder (sulfurous, brimstone)", "other": "Powder is extremely heavy"},
    {"die": "41-50", "color": "Green", "smell": "Newly-mown grass", "other": "Powder is magnetic (try licking a potion off your shield...)"},
    {"die": "51-60", "color": "Grey", "smell": "No smell", "other": "Powder is weightless or almost so"},
    {"die": "61-70", "color": "Orange", "smell": "Rot", "other": "Remains hotter or colder than room temperature"},
    {"die": "71-80", "color": "Purple", "smell": "Smoke", "other": "The powder's smell (other than 'no smell') is very, very strong"},
    {"die": "81-90", "color": "Red", "smell": "Vinegar", "other": "Tiny grains (dust-like)"},
    {"die": "91-00", "color": "White", "smell": "Wet dog", "other": "Very large grains (seed or gravel size)"},
]

# Table 3-164: Animal/Monster Part
ANIMAL_PRESERVATION = [
    "Suspension in liquid of the", "Distilled liquid of the", "Essence derived from the",
    "Oil pressed from the", "Paste made from the", "Pickled", "Powdered",
    "The Boiled", "The Dried", "The Mummified", "The Preserved", "The Salted",
    "The Smoke-cured"
]

ANIMAL_BODY_PARTS = [
    "Ankle-bone of a(n)", "Beak/tooth of a(n)", "Claw of a(n)", "Egg(s) of a(n)", 
    "Entrails of a(n)", "Eye of a(n)", "Face of a(n)", "Foot/hoof/claw of a(n)",
    "Gallstones of a(n)", "Hand of a(n)", "Head of a(n)", "Heart of a(n)",
    "Hide of a(n)", "Horn/antler/hair of a(n)", "Kidney of a(n)", "Knee-bone of a(n)",
    "Knucklebones or joints of a(n)", "Liver of a(n)", "Lungs of a(n)", "Remnants of a(n)",
    "Rib of a(n)", "Shin-bone of a(n)", "Skin or hide of a(n)", "Skull of a(n)",
    "Stomach of a(n)", "Teeth of a(n)", "Tongue of a(n)", "Tusk/fang/tooth of a(n)"
]

TYPE_A_MONSTERS = [
    "Anteater", "Ape", "Baboon", "Badger", "Bat", "Bear", "Beaver", "Boar", "Bull",
    "Camel", "Canary", "Cat", "Giant centipede", "Chicken", "Cobra", "Crab", "Crocodile",
    "Dinosaur", "Dog", "Dolphin", "Eagle", "Eel", "Elephant", "Fish", "Frog", "Giraffe",
    "Goat", "Hawk", "Heron", "Horse", "Hyena", "Jackal", "Demon Shark", "Leopard", "Lion",
    "Lizard", "Mammoth", "Monkey", "Octopus", "Ostrich", "Ox", "Parrot", "Peacock", "Roc",
    "Rabbit", "Rat", "Raven", "Rhinoceros", "Saber-tooth tiger", "Seal"
]

TYPE_B_MONSTERS = [
    "Basilisk", "Bugbear", "Catoblepas", "Cockatrice", "Crow", "Doppelganger", "Dove",
    "Dragon", "Dryad", "Duck", "Ferret", "Fire-Drake", "Ghoul", "Goblin", "Griffon",
    "Harpy", "Hippogriff", "Kobold", "Land Shark", "Leopard", "Lizard man", "Manticore",
    "Medusa", "Merman", "Minotaur", "Newt", "Ogre", "Panther", "Pixie", "Satyr",
    "Sea Monster", "Seagull", "Shark", "Snake", "Spider", "Squid", "Stag", "Swamp thing",
    "Toad", "Troglodyte", "Unicorn", "Viper", "Vulture", "Walrus", "Warthog", "Wereboar",
    "Werewolf", "Whale", "Wolf", "Wyvern"
]

ANIMAL_OTHER_DETAILS = [
    "Removed at Midsummer", "Removed by the light of a crescent moon", "Removed during an eclipse",
    "Removed during the Solstice", "Removed in a ritual conducted by a particular savage priesthood",
    "Removed in the dark of the New Moon", "Removed under the light of a full moon",
    "Slain (or found) in a forest", "Slain (or found) underground", "Slain with spears that were blessed by druids",
    "That could speak", "That died during a rainfall", "That died from being boiled",
    "That died from eating poisonous mushrooms", "That died from plague", "That died of old age",
    "That died of thirst", "That froze to death", "That had a rare spotted pattern of colors on it",
    "That had magical properties during life", "That had once eaten human flesh",
    "That inhabited the shores of a particular island", "That lived under a curse",
    "That was a blue-colored member of the species", "That was a half-blood with another species",
    "That was a perfect specimen of the species", "That was a perfectly black colored member of the species",
    "That was an albino of the species", "That was blind", "That was born at midnight",
    "That was born at the full moon", "That was born dead", "That was born on Midsummer Night",
    "That was cooked in oil immediately after death", "That was drowned", "That was fossilized",
    "That was killed by a ghost (or wraith, or spirit)", "That was killed by a predator",
    "That was killed by a virgin", "That was killed by members of its own species",
    "That was killed in a cage", "That was killed in a particular ancient ruin",
    "That was killed in a stone circle", "That was raised in captivity",
    "That was sacrificed in a particular location", "That was sacrificed on Allhallows Eve",
    "That was slain by a knight", "That was slain with a magical dagger",
    "That was slain with an arrow", "With two heads"
]

# Table 3-165: Person Part
PERSON_BODY_PARTS = [
    "Ankle-bone of a(n)", "Bladder of a(n)", "Blood of a(n)", "Brain of a(n)",
    "Dung of a(n)", "Ears of a(n)", "Entrails of a(n)", "Eye of a(n)", "Face of a(n)",
    "Final breath of a(n)", "Finger-bones of a(n)", "Fingernail of a(n)",
    "Fingers of a(n)", "Foot of a(n)", "Gallstones of a(n)", "Hair of a(n)",
    "Hand of a(n)", "Head of a(n)", "Heart of a(n)", "Heart's blood of a(n)",
    "Intestines of a(n)", "Kidney of a(n)", "Knee-bone of a(n)", "Knuckle-bones of a(n)",
    "Liver of a(n)", "Lungs of a(n)", "Rib of a(n)", "Shin-bone of a(n)", "Skin of a(n)",
    "Skull of a(n)", "Spittle of a(n)", "Stomach of a(n)", "Teeth of a(n)",
    "Thumbs of a(n)", "Toenails of a(n)", "Toes of a(n)", "Tongue of a(n)"
]

TYPE_P1_PERSON = [
    "Abbot", "Accused man", "Addict", "Adulterer", "Albino", "Alchemist", "Apothecary",
    "Arsonist", "Artisan", "Assassin", "Astrologer", "Baker", "Bandit", "Barbarian",
    "Barber", "Baron(ess)", "Beautiful woman", "Beggar", "Black-haired man", "Blackmailer",
    "Blasphemer", "Blond-haired person", "Blue-eyed man", "Bureaucrat", "Burglar",
    "Butcher", "Cattle Thief", "Counterfeiter", "Coward", "Desecrator of Tombs",
    "Deserter", "Dishonest Man", "Druid", "Drunk", "Dwarf", "Elf", "Embezzler",
    "Pirate", "Eunuch", "Executioner", "Extortionist", "Forger", "Gambler", "Goblin",
    "Grave Robber", "Handsome man", "Heretic", "Horse thief", "Judge", "Kidnapper"
]

TYPE_P2_PERSON = [
    "Knight", "Lawyer", "Necromancer", "Oathbreaker", "Ogre", "One-legged man", "Orc",
    "Peasant", "Perjurer", "Pickpocket", "Pirate", "Poisoner", "Prisoner", "Robber",
    "Rapist", "Red-haired man", "Shaman", "Slander", "Sailor", "Smuggler", "Swindler",
    "Tax Collector", "Traitor", "Trespasser", "Warlock", "Warrior", "Witch", "Widow",
    "Crone", "Seventh Son", "Halfling", "Noble", "Ferryman", "Foreigner", "Forester",
    "Fortune-teller", "Gladiator", "Knave", "Leper", "Outlaw", "Moneylender", "Monk",
    "Pilgrim", "Princess", "Shoemaker", "Spy", "Weaver", "Traveler", "Tailor"
]

# Table 3-166: Plant Part
PLANT_TYPES = [
    "Acacia gum", "Aconite", "Acorn, ground", "Adder's tongue", "Adderwort", "Adrue tubers",
    "Agaric", "Agrimony", "Alder-bark", "All-heal", "Almond", "Aloe", "Amaranth", "Angelica herb",
    "Anise oil", "Asparagus root", "Balmony", "Basil", "Beet", "Belladonna", "Betel nut",
    "Birch", "Birthwort", "Bittersweet", "Black Truffle", "Blackberry", "Bryony", "Burdock",
    "Butterbur", "Camphor", "Caraway seed", "Catnip", "Chamomile", "Clamshell mushroom",
    "Clover", "Cloves", "Comfrey", "Dandelion", "Death Cap mushroom", "Eyebright", "Fennel",
    "Feverfew", "Figwort", "Foxglove", "Garlic", "Gentian", "Ginger", "Ginseng",
    "Gypsy mushroom", "Hartstongue", "Hawthorn", "Hedgehog mushroom", "Hellebore",
    "Honeysuckle", "Horehound", "Horse mushroom", "Hyssop", "Ipecac", "Kelp", "Larkspur",
    "Leek", "Lily blossom", "Lily of the valley", "Lotus", "Mace", "Marigold", "Mayflower",
    "Melon seed", "Mint", "Mistletoe", "Mullein", "Mustard", "Myrrh", "Nutmeg",
    "Old Man of the Woods mushroom", "Parasol mushroom", "Passion-flower", "Pepper",
    "Peppermint", "Pomegranate", "Poppy", "Quince", "Rose", "Rose hips", "Saffron",
    "Scaber Stalk mushroom", "Sesame seeds", "Shaggy Mane mushroom", "Skullcap Root",
    "Smearwort", "Sweetbalm", "Tarragon", "Tea", "Thyme", "Tree Ear mushroom",
    "Trumpet of Death mushroom", "Valerian Root", "Watercress", "Willow", "Woodbine"
]

PLANT_OTHER_DETAILS = [
    "Blessed by a monk before preparation", "Brought from across the sea", "Brought from the far west",
    "Buried for a year in a crossroads before preparation", "Collected by a widow",
    "Cooked in a rare beer before preparation", "Cooked in demon-fire before preparation",
    "Cut by a man condemned to be beheaded", "Cut by the wife of a soldier",
    "Dug from the ground by a murderer", "Dusted with crushed mother of pearl",
    "Dusted with the powdered teeth of a wolf", "Fertilized with the manure of wild hippogriffs",
    "Fertilized with the rotted meat of an ogre", "Grown beneath a canopy of spider-webs",
    "Grown beneath a lens of amber", "Grown by dwarves", "Grown by evil elves", "Grown by goblins",
    "Grown by witchcraft", "Grown from the empty eye socket of a skull",
    "Grown from the grave-earth of a murderer", "Grown from the grave-earth of a saint",
    "Grown in a cursed glade", "Grown in a forest where ghosts dwell", "Grown in a graveyard",
    "Grown in a house of glass", "Grown in a nest of vipers", "Grown in a room of mirrors",
    "Grown in a swamp", "Grown in an ancient battlefield", "Grown in clay pots",
    "Grown in earth that was kept isolated", "Grown in elemental earth", "Grown in hanging baskets",
    "Grown in the high mountains", "Grown in the nest of a roc", "Grown in the precincts of a prison",
    "Grown in the precincts of a temple", "Grown in the ruins of a settlement", "Grown in the snow and ice",
    "Grown in the tidal pools", "Grown in waters that have drowned a man",
    "Grown near the nests of giant wasps", "Grown on a particular mountain peak", "Grown without sunlight",
    "Harvested at dawn", "Harvested at Dusk", "Harvested at midnight", "Harvested at Midsummer",
    "Harvested at the full moon", "Harvested at the Winter Solstice", "Harvested by a child",
    "Harvested by a druid", "Harvested by a traitor", "Harvested by a virgin", "Harvested by goblins",
    "Harvested by night", "Harvested by one whose soul is damned", "Harvested by the alchemist",
    "Harvested during an eclipse", "Harvested during the new moon", "Harvested in the teeth of a gale",
    "Harvested on Allhallows Eve", "Harvested under a crescent moon", "Harvested with a blade that has recently killed",
    "Harvested with a copper sickle", "Harvested with a magical blade", "Mixed with olives",
    "Nourished with elemental water", "Passed through the gut of a monkey", "Prepared after harvesting by use of elemental fire",
    "Prepared by a blind man", "Prepared by a dryad", "Prepared by a gypsy", "Prepared by a witch",
    "Prepared so as to be highly flammable", "Prepared so as to repel magical creatures",
    "Prepared so as to sublimate into a poison gas", "Scorched in a fire of rare woods",
    "Soaked in the water from a particular lake", "Stolen from a druidic grove",
    "Stolen from a merchant of evil reputation", "Taken from the gardens of a titan",
    "That has had dark spells cast upon it", "That has heard sounds of pure terror",
    "That has survived a forest fire", "That was watered with blood", "Using rare vinegars and oils",
    "Washed with the tears of a damsel"
]

# Table 3-167: Small Alchemical Things
SMALL_THING_TYPES = [
    "Bats", "Bees", "Beetles", "Blossoms, buds, or flowers", "Brains", "Cats", "Centipedes",
    "Crabs", "Dragonflies", "Earwigs", "Eels", "Feathers", "Frogs", "Gallstones", "Geckos",
    "Hornets", "Horrid things from under the water", "Imps", "Jellyfish", "Lamprey",
    "Leeches", "Locusts", "Mice", "Mold or lichen", "Moths", "Mushrooms or truffles",
    "Newts", "Octopus-creatures", "Ooze-globules", "Piranha", "Praying Mantises", "Rats",
    "Roaches", "Scarab beetles", "Shrews", "Slugs", "Snails", "Snakes", "Songbirds",
    "Spiders", "Stink bugs", "Tapeworms", "Tentacles", "Ticks", "Toads", "Turtles",
    "Vines or tendrils", "Wasps", "Worms"
]

SMALL_THING_PRESERVATION = [
    "Distilled", "Dried", "Ground-up", "Jellied", "Pickled", "Powdered", "Salt-cured",
    "Smoke-cured", "Smoked", "Stewed"
]

# Table 3-168: Substance
SUBSTANCE_FORMS = [
    "Chips", "Cubes", "Disks", "Flakes", "Granola-like lumps", "Granules", "Gravel",
    "Chunks of gummy, jelled, or oozy form", "Nuggets", "Pebbles", "Polyhedrons",
    "Powder (fine)", "Powder (regular)", "Rocks", "Sequins", "Slices",
    "Small cylinders or sticks", "Strands, hairs, or filaments", "Wafers", "Wire"
]

SUBSTANCE_TYPES = [
    "Amber", "Brimstone (sulfur)", "Bronze or brass", "Chalcedony or malachite",
    "Chitin, shell, or carapace", "Coal", "Emerald, ruby, or sapphire",
    "Frozen ichor or blood", "Frozen potion", "Gold or silver", "Incense or wood",
    "Iron or steel", "Normal rock", "Obsidion or turquoise", "Opal or jade",
    "Pearl or mother-of-pearl", "Rust", "Salt", "Solidified chemicals", "Solidified smoke/fire/gas"
]

SUBSTANCE_OTHER = [
    "Found as a byproduct of a dimensional gateway", "Found in the guts of a leviathan",
    "Found in the sea bed off a particular coast", "Found in the seeds of a rare plant",
    "From the bark of a bizarre underground tree", "Mined by evil dwarves or goblins",
    "Mined by genies or ifreet", "Mined from a volcano", "Mined from the lair of a demon",
    "Mined from the precincts of an elemental power", "Mined from the rock beneath a holy site",
    "Mined from the deepest level of a cavern complex", "Obtained from the eggs of a bizarre creature",
    "Prepared by a wizard", "More magical and sinister than it appears",
    "Disturbingly kept appearing in the lab", "Obtained high in the clouds",
    "Obtained by trading with extra-dimensional creatures", "Byproduct of the main project"
]

BENEFICIAL_EFFECTS = [
    "Removes a particular curse or bad magical effect",
    "Temporarily increases ability to cast spells",
    "Improves ability to hear",
    "Improves ability to smell",
    "Grant ability to see beyond normal parameters (dark, plane of existence, invisible)",
    "Improves ability to see",
    "Improves effect of sleep (double healing or less required)",
    "Temporarily improves ability to speak (languages or persuasion)",
    "Ability to speak with dead or a particular corpse's spirit",
    "Ability to transform into a particular animal shape (temporary)",
    "Improves ability to turn undead (or temporary grant)",
    "Improved alertness",
    "Attribute increase: Charisma",
    "Attribute increase: Dexterity",
    "Attribute increase: Intelligence",
    "Attribute increase: Strength",
    "Attribute increase: Wisdom",
    "Chance to regain a spell after casting or cast twice",
    "Ability to dig like a badger at high speed",
    "Permanent immunity to a particular disease",
    "Temporary immunity to all diseases",
    "Immune to damage from blunt weapons",
    "Immune to damage from cutting or piercing weapons",
    "Character becomes physically more youthful",
    "Character can command a particular type of animal",
    "Gain info about objects by touching them",
    "Can see around corners somehow",
    "Character does not need sleep",
    "Gains a temporary gaze attack (petrify, paralyze, charm)",
    "Gains rations or supplies",
    "Gains treasure (coins)",
    "Gains treasure (gems or jewelry)",
    "Gains treasure (magic item)",
    "Noiseless movement",
    "No scent, undetectable by smell",
    "Can elongate arms like rubber",
    "Fully healed or gain temporary hit points",
    "Healed of damage",
    "Ability to speak/read/understand a new language permanently",
    "Bonus to hit or damage against a particular monster type",
    "Receives useful information (mental/vision/document)",
    "Equipment is improved (repaired or cleaned)",
    "Equipment is improved (bonus to arms/armor)",
    "Laughter causes temporary fear effect",
    "Skin becomes tougher (improved AC)",
    "Various items to take (uncertain value)",
    "Cures diseases",
    "Direct vision of deity/blessing conferred",
    "Food provides hit point restoration",
    "Sleep confers dreams with info or double healing",
    "Temporarily increased efficacy of spells",
    "Fighting bonus: against a particular foe type",
    "Fighting bonus: to damage only",
    "Fighting bonus: to hit",
    "Fighting bonus: to hit and damage",
    "Temporary spellcasting ability (Cleric/Magic-user level)",
    "Gain experience points",
    "Gain level",
    "Gain magical ally (stone dog, air spirit)",
    "Grants wish",
    "Heightened sense (taste, smell, feel)",
    "Immunity to certain spells (sleep, slow)",
    "Immunity: particular temperature (heat or cold)",
    "Immunity: acid, electricity, or poison",
    "Immunity: charm-type effects",
    "Information: map or vision of surrounding area",
    "Information: how to reach a particular objective",
    "Information: command word to activate effect or bypass risk",
    "Location: teleported to another location or plane",
    "Location: stairs open to another level",
    "Magic resistance",
    "Monsters summoned to assist and follow orders",
    "Monsters tend to ignore character (temporary)",
    "Partial immunity: elemental magic",
    "Animal becomes a loyal ally",
    "Saving throw bonus: particular type of threat",
    "Saving throw bonus: in particular area",
    "Saving throw bonus: on all saves (temporary)",
    "Sense of direction (north, depth, or destination)",
    "Small gift: fine clothing, hat, trophy, medallion",
    "Special ability: cast charm effect",
    "Special ability: cast protective spell",
    "Special ability: change form",
    "Special ability: regeneration",
    "Special ability: speak to animals",
    "Special ability: unusual climbing/swinging/jumping",
    "Special ability: invisible but casts a shadow",
    "Special ability: breathe water",
    "Special ability: cannot be entangled (temporary)",
    "Special ability: detect thoughts",
    "Special ability: levitation or flying (temporary)",
    "Special ability: produce light at will",
    "Special ability: see through or pass through stone",
    "Additional attacks or actions",
    "Speed: strikes first",
    "Increased movement rate",
    "Temporary access to a treasure trove",
    "Receives a key to open a particular door/bypass trap",
    "Opens otherwise impassable door/portcullis",
    "The item will raise one person from the dead"
]

CURSES = [
    "Ability to cast spells removed",
    "Ability to hear reduced",
    "Ability to hear removed",
    "Ability to see reduced",
    "Ability to see removed",
    "Ability to sleep reduced (healing)",
    "Ability to sleep removed",
    "Ability to speak intelligently removed",
    "Ability to speak removed",
    "Ability to touch/manipulate reduced (hands change or force field)",
    "Ability to use sense (taste, smell, feel) removed",
    "Alertness reduced",
    "Alertness removed",
    "Alignment changed",
    "Attribute reduced: Charisma",
    "Attribute reduced: Dexterity",
    "Attribute reduced: Intelligence",
    "Attribute reduced: Strength",
    "Attribute reduced: Wisdom",
    "Aversion created",
    "Aging to the point of disability",
    "Aging with no ill effect",
    "Fast aging leading to death (days/weeks/months)",
    "Random sleeping episodes (narcolepsy)",
    "Causes sleep",
    "Magnet for attacking monsters",
    "Gain ability (e.g. fire breathing) but with bad side effect",
    "Gain uncontrollable/random power",
    "Gives off smell, attracting monsters",
    "Gives off sound, attracting monsters",
    "Attacked by tentacles or created monster",
    "Given false information",
    "Isolated from party (pit, cage, dimensional prison)",
    "Secretly given mission (unable to communicate)",
    "Sense of purpose reduced",
    "Charm response: victim acts in particular way",
    "Charm commands: victim must follow limited orders",
    "Charm mental commands: orders to victim",
    "Charm word: victim acts in particular way when word spoken",
    "Charm attack: victim allows monster to attack",
    "Charm confusion: acts randomly",
    "Charm friendly: follows suggestions",
    "Charm puppet: mentally controlled",
    "Charm flee",
    "Charm emotion: random debilitating emotion",
    "Charm control: emotions controlled",
    "Death magic (becoming zombie/wraith after death)",
    "Normal Disease",
    "Virulent Disease",
    "Food causes small damage or prevents sleep",
    "Sleep causes bad smell, teleportation, or affects others",
    "Efficacy of attacks reduced (damage)",
    "Efficacy of spells reduced",
    "Failure chance on spells",
    "Fighting penalties (against particular species)",
    "Fighting penalties (damage only)",
    "Fighting penalties (to hit and damage)",
    "Fighting penalties (to hit only)",
    "Hit point damage",
    "Intelligibility of speech becomes random",
    "Level drain",
    "Location: moved to another level (mechanism)",
    "Location: teleported to another location or plane",
    "Loss or penalty to turning ability",
    "Healing (magical or natural) does not affect character",
    "Monsters summoned and focus on character",
    "Movement rate reduced",
    "Paralysis (permanent until removed)",
    "Party distrust",
    "Physical appearance (boils, length of nose)",
    "Physical appearance change (no game effect, e.g. head of donkey)",
    "Physical transformation: part of character becomes animal part",
    "Physical transformation: change under specific conditions (combat, damage)",
    "Physical transformation: cyclical/periodic changes",
    "Physical transformation: into animal",
    "Physical transformation: into animal",
    "Physical transformation: into object",
    "Physical transformation: into object",
    "Physical transformation: into substance",
    "Physical transformation: into substance",
    "Rate of attacks reduced",
    "Rations/water supply poisoned or destroyed",
    "Sacrifice treasure to overcome obstacle",
    "Permanent insanity (debilitating)",
    "Permanent insanity (mild)",
    "Temporary insanity",
    "Saving throws: permanent penalty",
    "Saving throws: temporary penalty (timed)",
    "Saving throws: penalty until particular action taken",
    "Sense of direction affected (lost easily)",
    "Sense of taste/feel/smell always unpleasant",
    "Sex change",
    "Speed: strike last",
    "Half movement and attack rate",
    "Turns into gas or liquid",
    "Style of movement altered (physical transformation)",
    "Uncontrollable ability in combat (berserk, size, fire)",
    "Cursed effect if character dies (no raise dead/undead)",
    "Equipment (leather/wood/metal/etc) affected",
    "Willingness to fight reduced"
]

def roll_d100():
    return random.randint(1, 100)
