# Table 3-181: Gems and Precious Stones
GEMS = {
    (1, 2): {"name": "Agate", "description": "A form of chalcedony. Often shows beautiful banding and stripes."},
    (3, 4): {"name": "Agate Geode", "description": "Rock nodules containing agate inside. Dramatic when cut open."},
    (5, 6): {"name": "Amber", "description": "Fossilized tree resin. Usually with a yellowish cast; occasionally contains insects."},
    (7, 8): {"name": "Amethyst (Purple)", "description": "A variety of quartz. Believed by the Romans to prevent drunkenness."},
    (9, 10): {"name": "Amethyst (Yellow)", "description": "A yellow form of amethyst."},
    (11, 12): {"name": "Apatite", "description": "Green and blue colored; occasionally chatoyant (cat's-eye)."},
    (13, 14): {"name": "Aquamarine", "description": "A blue form of beryl."},
    (15, 16): {"name": "Beryl", "description": "Pure beryl is transparent; impurities give it color."},
    (17, 18): {"name": "Bloodstone", "description": "Dark green chalcedony flecked with spots of red jasper; also called Heliotrope."},
    (19, 20): {"name": "Carnelian", "description": "A red form of chalcedony."},
    (21, 22): {"name": "Chalcedony", "description": "A translucent gemstone with a waxy-looking surface."},
    (23, 24): {"name": "Chrysoprase", "description": "Green chalcedony."},
    (25, 26): {"name": "Coral", "description": "Can be carved and polished; comes in a wide range of colors."},
    (27, 28): {"name": "Diamond", "description": "Usually clear; impurities can result in almost any color."},
    (29, 30): {"name": "Diamond (Black)", "description": "Fabulously rare in fantasy worlds."},
    (31, 32): {"name": "Diamond (Blue)", "description": "Resulting from boron impurities; rarer than normal diamonds."},
    (33, 34): {"name": "Emerald", "description": "The green form of beryl. Rare and valuable."},
    (35, 36): {"name": "Feldspar", "description": "Common mineral; moonstone is a lustrous and attractive form."},
    (37, 38): {"name": "Garnet", "description": "Comes in a variety of colors; some change color depending on light."},
    (39, 40): {"name": "Golden Beryl", "description": "A golden yellow form of beryl, often called Heliodore."},
    (41, 42): {"name": "Hematite", "description": "A metal, iron oxide, varying from steel-colored to black or red."},
    (43, 44): {"name": "Ivory", "description": "Comes from tusks; can be carved and polished."},
    (45, 46): {"name": "Jade (Black)", "description": "Very valuable in a fantasy world as it doesn't exist in reality."},
    (47, 48): {"name": "Jade (Blue)", "description": "A blue form of jade."},
    (49, 50): {"name": "Jade (Green)", "description": "The most valuable form of natural jade."},
    (51, 52): {"name": "Jasper", "description": "Opaque chalcedony; colors include red, yellow, brown, and green."},
    (53, 54): {"name": "Lapis Lazuli", "description": "A blue, relatively rare semi-precious stone."},
    (55, 56): {"name": "Malachite", "description": "A vibrant green, relatively common stone."},
    (57, 58): {"name": "Moonstone", "description": "A form of feldspar that looks pearl-like and reflects light from inside."},
    (59, 60): {"name": "Moss Agate", "description": "Agate containing filament-like patterns that look like plants."},
    (61, 62): {"name": "Mother of Pearl", "description": "Pearl-like deposits from mollusks or giant clams."},
    (63, 64): {"name": "Obsidian", "description": "Volcanic glass; dark colored and capable of very sharp edges."},
    (65, 66): {"name": "Onyx", "description": "A form of banded quartz."},
    (67, 68): {"name": "Opal", "description": "Ranges widely in color; has many internal colors together."},
    (69, 70): {"name": "Opal (Black)", "description": "The rarest kind of opal; can have black and red combinations."},
    (71, 72): {"name": "Opal (Fire)", "description": "Predominantly red with internal black colorations."},
    (73, 74): {"name": "Pearl", "description": "Formed in oysters; sea pearls are rarer than freshwater ones."},
    (75, 76): {"name": "Pearl (Black)", "description": "Very rare color of sea pearl found in the real world."},
    (77, 78): {"name": "Pearl (Purple)", "description": "A rare color of sea pearl."},
    (79, 80): {"name": "Peridot", "description": "An olive-green gemstone; has even been found in meteorites."},
    (81, 82): {"name": "Quartz (Rose)", "description": "A particular pink color of quartz."},
    (83, 84): {"name": "Quartz (Smoky)", "description": "A particular dark, smoky color of quartz."},
    (85, 86): {"name": "Ruby", "description": "One of the four true precious stones; pink to dark red corundum."},
    (87, 88): {"name": "Sapphire", "description": "One of the four true precious stones; any color of corundum except red."},
    (89, 90): {"name": "Sapphire (White)", "description": "Extremely valuable; no such thing in the real world."},
    (91, 92): {"name": "Tiger's Eye", "description": "A chatoyant form of quartz that looks like an eye."},
    (93, 94): {"name": "Topaz (any)", "description": "Pure topaz is colorless."},
    (95, 96): {"name": "Topaz (blue)", "description": "Blue is the rarest color of topaz."},
    (97, 98): {"name": "Tourmaline", "description": "A semi-precious stone found in almost any color."},
    (99, 100): {"name": "Turquoise", "description": "Can be blue, green, or red, often with veins of color."},
}
