# Shared Settlement Logic Tables (Villages & Cities)

PRIDE_OF_TOWN = {
    2: "A local 'wonder of the world' (a collection, museum, or library)",
    4: "A local 'wonder of the world' (a statue)",
    6: "A local 'wonder of the world' (a structure)",
    8: "A local 'wonder of the world' (animal or beast)",
    10: "A local 'wonder of the world' (plant or tree)",
    12: "A local recipe/dish (e.g. Silverport-style fried rat)",
    14: "A local strongman",
    16: "Beauty of the women",
    18: "Cleanliness of the people",
    20: "Cleanliness of the town",
    22: "Comfortable beds",
    24: "Elaborate or constant insults",
    26: "Flamboyance of local clothing",
    28: "Good manners",
    30: "Hospitality to foreigners",
    32: "Local bread",
    34: "Local cats",
    36: "Local entertainers (juggling, etc.)",
    38: "Local livestock",
    40: "Local meats",
    42: "Local music",
    44: "Local political leaders or political system",
    46: "Local tea",
    48: "Local temple(s)",
    50: "Manners or skill of town watch",
    52: "Masonry",
    54: "Metalwork",
    56: "Obedience",
    58: "Odd physical feature such as overbite or large eyes",
    60: "Quality of glassblowing products",
    62: "Quality of local food or cooking",
    64: "Quality of pottery or ceramics",
    66: "Quality of sailors (If city/town is a port)",
    68: "Quality of teeth",
    70: "Remarkable fatness or thinness of locals",
    72: "Remarkable height of citizens",
    74: "Security of local prison",
    76: "Severity of laws",
    78: "Size of local fair",
    80: "Size or taste of the local vegetables",
    82: "Skill at a game (chess, discus-throwing, etc.)",
    84: "Skill of animal breeders",
    86: "Skill of local merchants",
    88: "Skill of local soldiers",
    90: "Skill of locals at trading and haggling",
    92: "Statues",
    94: "Taverns/beer",
    96: "Textiles",
    98: "Wine",
    100: "Woodcarving"
}

DRAFT_ANIMALS = {
    5: "Aurochs",
    10: "Dinosaurs (biped)",
    15: "Dinosaurs (quadruped)",
    20: "Elephants (or mammoths)",
    25: "Floating fungus (big levitating mushroom-caps you ride on)",
    30: "Giant dogs or cats (or wolves)",
    35: "Giant goats (mountain goats)",
    40: "Giant lizards",
    45: "Giant ostriches",
    50: "Giant serpents",
    55: "Giant peacocks",
    60: "Giant rodent",
    65: "Giant turtles",
    70: "Giant walking air-breathing fish (sharks, whales, etc)",
    75: "Hippopotamus",
    80: "Massive insects (for flying) or beetles",
    85: "Mutant horses (chitin armor, horns, etc.)",
    90: "Mutated giant animal",
    95: "Rhinoceros",
    100: "Yaks"
}

STRANGE_DRESS_WHO = {
    5: "All Women",
    10: "All Men",
    15: "All married people",
    20: "All members of a particular profession (Wizards, Fighters, etc.)",
    25: "All members of a particular bloodline or species",
    30: "All members of a particular religion",
    35: "All members of one particular guild",
    40: "All people who are not members of one of the city's official guilds",
    45: "All People (residents and visitors)",
    50: "All Residents",
    55: "All unmarried people",
    60: "All visitors",
    65: "All who are parents",
    70: "Anyone who has passed some sort of test or challenge",
    75: "Criminals of a particular type",
    80: "Each odd-numbered visitor",
    85: "Members of a certain political faction",
    90: "Members of a particular social class",
    95: "Members of each political faction have a certain identify mode",
    100: "Members of each social class have a distinctive article"
}

STRANGE_DRESS_WHAT = {
    5: "A box or other small container",
    10: "A particular item of clothing (specific color)",
    15: "Badge, embroidered or sewn with relevant identification",
    20: "Bells (jingling to cowbell size)",
    25: "Facial marking (paint, henna, etc.)",
    30: "Feathers from a particular flying creature",
    35: "Flowers",
    40: "Gloves, tights, or codpiece",
    45: "Item of silverware (e.g. specific spoon)",
    50: "Mask or veil",
    55: "Metal collar, bracelet, or non-decorative piece",
    60: "Nose ring or earring(s)",
    65: "Overlong sleeves or no sleeves (vest)",
    70: "Pointed hat (1d3+1 points)",
    75: "Pointed shoes (boots or slippers)",
    80: "Ribbons",
    85: "Specific type of relic from your family",
    90: "Tattoo or ritual scarring",
    95: "Wide-brimmed hat, hat with no brim, or specific hood",
    100: "Wooden shoes, high boots, sandals, or other specific footwear"
}

ODD_BEHAVIOR = {
    10: "Avoid all eye contact",
    20: "Bow constantly",
    30: "Distinctive swear word or expostulation",
    40: "Nod throughout another’s speech",
    50: "Refer to oneself only in the third person",
    60: "Snap fingers when agreeing (or disagreeing)",
    70: "Tap self when agreeing (head, foot, heart)",
    80: "Two-part gesture for greeting (e.g. clap hands then bow)",
    90: "Wave hand in particular way",
    100: "Wiggle earlobes or nose with fingers"
}

CULTURAL_GRAVITY = {
    10: "Actual worship of ruling class",
    20: "Dedication to stamping out some type of art, poetry, or lifestyle",
    30: "Focused on the community rather than the individual",
    40: "Obsessively focused on a 'living god' in the community",
    50: "Obsessively focused on cleanliness",
    60: "Obsessively focused on physical health",
    70: "Obsessively focused on religion",
    80: "Obsessively focused upon a particular statue",
    90: "Obsessively focused upon sex",
    100: "Rigid adherence to dictates left by the community's founder"
}
