import random

BASIC_MECHANICAL_TRAPS = {
    (1, 2): "Adhesive, on surfaces",
    (3, 4): "Alcove, guillotine blade",
    (5, 6): "Area temperature change",
    (7, 8): "Bear trap or other spring-loaded object",
    (9, 10): "Breaking bridge",
    (11, 12): "Caltrops",
    (13, 14): "Ceiling drops",
    (15, 16): "Ceiling lowers",
    (17, 18): "Ceiling or floor becomes magnetic",
    (19, 20): "Chemical reaction in floor, walls, or ceiling, releases gas",
    (21, 22): "Door, falls to crush",
    (23, 24): "Fire increases",
    (25, 26): "Floor rises to meet ceiling",
    (27, 28): "Floor, becomes magnetic",
    (29, 30): "Floor, flips over",
    (31, 32): "Floor, tilts toward something unpleasant",
    (33, 34): "Grate, spiked, drops",
    (35, 36): "Grease or other slippery substance",
    (37, 38): "Iron bar swings to hit",
    (39, 40): "Ladder rungs break",
    (41, 42): "Large object pulled or pushed to crush",
    (43, 44): "Log swings to hit",
    (45, 46): "Magnetism",
    (47, 50): "Missile Trap",
    (51, 52): "Net (pull up, drop down)",
    (53, 54): "Pit trap",
    (55, 56): "Portcullis falls",
    (57, 58): "Quicksand",
    (59, 60): "Rolling ball",
    (61, 62): "Room, fills with sand or gravel",
    (63, 64): "Room, floods with water",
    (65, 66): "Scything blade",
    (67, 68): "Snare or noose, pulls sideways",
    (69, 70): "Snare or noose, pulls up",
    (71, 72): "Spiked ball (or other heavy object) swings to hit",
    (73, 74): "Squirt-trap fires glue",
    (75, 76): "Stairs break",
    (77, 78): "Stone block, drops to block passage behind",
    (79, 80): "Stone block, drops to crush",
    (81, 82): "Stone cylinder (huge) rolls into trapped area",
    (83, 84): "Surface turns into slide or chute",
    (85, 86): "Trapdoor opens",
    (87, 88): "Valve, releases gas",
    (89, 90): "Valve, releases liquid",
    (91, 92): "Vent, releases very strong wind or gust",
    (93, 94): "Vent: releases gas",
    (95, 96): "Wall, close in",
    (97, 98): "Wall, opens to release monsters",
    (99, 100): "Webs"
}

TRAP_CONCEALMENT = {
    (1, 2): "Alcove",
    (3, 4): "Altar",
    (5, 6): "Aquarium",
    (7, 8): "Barrel or cask",
    (9, 10): "Bath or basin",
    (11, 12): "Bed",
    (13, 14): "Book",
    (15, 16): "Bookshelves",
    (17, 18): "Box or crate",
    (19, 20): "Bridge",
    (21, 22): "Cabinet",
    (23, 24): "Carpet or rug",
    (25, 26): "Ceiling hook",
    (27, 28): "Chair or throne",
    (29, 30): "Chest",
    (31, 32): "Corpse",
    (33, 34): "Dais, platform or stage",
    (35, 36): "Desk",
    (37, 38): "Display case",
    (39, 40): "Door",
    (41, 42): "Door hinges",
    (43, 44): "Doorknob or latch",
    (73, 74): "Pillar or column",
    (75, 76): "Pool",
    (77, 78): "Portcullis",
    (79, 80): "Railing",
    (81, 82): "Ramp",
    (83, 84): "Stairs",
    (85, 86): "Stove",
    (87, 88): "Sundial",
    (89, 90): "Table",
    (91, 92): "Tapestry",
    (93, 94): "Taxidermy piece",
    (95, 96): "Telescope or kaleidoscope",
    (97, 98): "Toilets or privy",
    (99, 100): "Torch or sconce"
}

COMPLICATED_TRIGGER = {
    (1, 2): "A chemical requires a certain level of coolness to remain inactive. Nearby flames (such as torches) cause it to react and activate the trap",
    (3, 4): "A chemical requires a certain level of heat to remain inactive. Shadows cause it to react and activate the trap",
    (5, 6): "A coating of grease covers a substance that heats up when exposed to air; if the grease is smeared, the heat of the chemical reaction activates the trap",
    (7, 8): "A feather is suspended over a very delicate pressure plate. If it is blown down by air currents, it will activate the trap when it lands (so would other very light objects)",
    (9, 10): "A glass globe (possibly quite small) contains a chemical that is highly reactive when exposed to air. If the globe breaks (and is still in the right place) the heat of the chemical reaction activates the trap",
    (11, 12): "A hanging object or an object resting on the floor holds down a vertical tripwire. If the object is removed, the tripwire flies into the ceiling (probably due to a counterweight) and the trap is activated",
    (13, 14): "A highly reactive powder is located upon a heat sensor of some kind. Body heat, oils in skin, or exhaled carbon dioxide concentrations (three different triggers, here) cause the powder to react and activate the heat sensor or burn through a thread",
    (15, 16): "A part of the item can be moved, and contains a lever that activates the trap",
    (17, 18): "Acid container tips onto string; when spring snaps, trap is activated",
    (19, 20): "Acid container tips onto string; when spring snaps, trap is activated",
    (21, 22): "Beam of light (possibly invisible, possibly not, possibly visible only with unusual type of vision) has a 'photoreceptor': if the beam of light is broken, the trap is activated",
    (23, 24): "Something blocks a beam of light, but if that item is moved, the light will hit a photoreceptor and activate the trap",
    (25, 26): "Beam of light (possibly invisible, possibly not, possibly visible only with unusual type of vision) has a 'photoreceptor': if the beam of light is broken, the trap is activated",
    (27, 28): "Something blocks a beam of light, but if that item is moved, the light will hit a photoreceptor and activate the trap",
    (29, 30): "Blade cuts twine if moved",
    (31, 32): "Blade cuts twine if moved",
    (33, 34): "Change-up. A hammer is held suspended by a latch, which, if opened will cause the hammer to strike an obvious pressure plate. That pressure plate HAS to be hit in order to temporarily de-activate another, hidden, pressure plate in the floor.",
    (35, 36): "Flint sparks a trail of flammable powder to the triggering point",
    (37, 38): "Flint sparks a trail of flammable powder to the triggering point",
    (39, 40): "Guitar-type string, if plucked, establishes a frequency that breaks a little sliver of glass, activating the trap",
    (41, 42): "Latch releases gears to begin moving, if the latch is accidentally pulled off its holder",
    (43, 44): "Latch releases gears to begin moving, if the latch is accidentally pulled off its holder",
    (73, 74): "Sliding bolt keeps hidden gears from moving unless the bolt is pulled from its socket",
    (75, 76): "Sliver of blown glass contains a light beam or a corrosive liquid that activates the trap if the piece of glass is broken",
    (77, 78): "Something is delicately balanced upon a button. If it falls, the removal of weight lifts a pin and activates the trap",
    (79, 80): "Spring releases trap",
    (81, 82): "Spring releases trap",
    (83, 84): "Trap is located on a balanced 'seesaw' with another counterweight; if either item is removed, the seesaw will press onto a trigger and activate the trap",
    (85, 86): "Trap is located on a balanced 'seesaw' with another counterweight; if either item is removed, the seesaw will pull up a chain and activate the trap",
    (87, 88): "Trap is located on a balanced 'seesaw' with another counterweight; if either item is removed, the seesaw will press onto a trigger and activate the trap",
    (89, 90): "Trap is located on a balanced 'seesaw' with another counterweight; if either item is removed, the seesaw will pull up a chain and activate the trap",
    (91, 92): "Tripwire activates trap when pulled",
    (93, 94): "Tripwire activates trap when pulled",
    (95, 96): "Tripwire activates trap when pulled",
    (97, 98): "Tripwire activates trap when pulled",
    (99, 100): "Water container in trap, if disturbed, splashes water onto reactive substance; chemical reaction releases trap"
}

def get_from_table(table, roll):
    for (low, high), value in table.items():
        if low <= roll <= high:
            return value
    return "Unknown"

GAS_EFFECTS = {
    (1, 2): "Affects brain (confusion): causes random actions (temporary)",
    (3, 4): "Affects brain (language): lose language or speech capability (temporary).",
    (5, 6): "Affects brain (rage): attack comrades (temporary)",
    (7, 8): "Affects muscles: can only carry half normal weight (permanent)",
    (9, 10): "Affects muscles: can only carry half normal weight (temporary)",
    (11, 12): "Affects muscles: causes damage penalty (permanent)",
    (13, 14): "Affects muscles: causes damage penalty (temporary)",
    (15, 16): "Affects muscles: movement rate reduced by half (permanent)",
    (17, 18): "Affects muscles: movement rate reduced by half (temporary)",
    (19, 20): "Affects nerves: causes to-hit penalties (permanent)",
    (21, 22): "Affects nerves: causes to-hit penalties (temporary)",
    (23, 24): "Affects nerves: saving throw penalties (permanent)",
    (25, 26): "Affects nerves: saving throw penalties (temporary)",
    (27, 28): "Affects nerves; palsy prevents character from being able to hold onto anything (temporary)",
    (29, 30): "Affects skin: rash and itching (various effects possible, from combat penalties to saving throws to taking off armor, to dropping held items - long term but not permanent)",
    (31, 32): "Attacks brain (intelligence): lowers intelligence (permanent)",
    (33, 34): "Attacks brain (intelligence): lowers intelligence (temporary)",
    (35, 36): "Attacks muscles: lowers strength (permanent)",
    (37, 38): "Attacks muscles: lowers strength (temporary)",
    (39, 40): "Attacks nerves: lowers dexterity (permanent)",
    (41, 42): "Attacks nerves: lowers dexterity (temporary)",
    (43, 44): "Attacks respiratory system: causes hit point damage (less with saving throw)",
    (45, 46): "Blindness gas",
    (47, 48): "Burns skin: reduces charisma (permanent)",
    (49, 50): "Burns skin: reduces charisma (temporary)",
    (51, 52): "Causes depression and lethargy: affected characters won\u2019t bother going anywhere or fighting (temporary)",
    (53, 54): "Damaging gas: more or less hit point damage depending on saving throw.",
    (55, 56): "Fear gas: combat penalties (temporary)",
    (57, 58): "Fear gas: paralyzed (temporary)",
    (59, 60): "Fear gas: run (temporary)",
    (61, 62): "Flammable",
    (63, 64): "Flammable: sticks to clothing and skin for ongoing damage if ignited",
    (65, 66): "Forgetfulness gas (possibly just role-played, or possibly a loss of experience points or even levels).",
    (67, 68): "Hallucination gas; 50% likelihood of attacking a double image of opponents (temporary)",
    (69, 70): "Hallucination gas; see friends as some sort of enemy (works best if that sort of enemy is waiting for the gas to take effect before attacking) (temporary).",
    (71, 72): "Hunger gas: consume all rations",
    (73, 74): "Light sensitivity gas: light causes damage, but you still can\u2019t see very well in the dark (some sort of partial blindness) (temporary)",
    (75, 76): "Pain gas: victims are incapacitated to some degree (e.g., drop weapons, effectively paralyzed, or just subject to combat penalties).",
    (77, 78): "Paralysis (temporary)",
    (79, 80): "Poison",
    (81, 82): "Poison",
    (83, 84): "Poison",
    (85, 86): "Poison",
    (87, 88): "Poison",
    (89, 90): "Poison",
    (91, 92): "Removes oxygen from air (affects breathing and flames)",
    (93, 94): "Sleep gas",
    (95, 96): "Slow gas, causes all effects of a slow spell (temporary)",
    (97, 98): "Tightens throat muscles, causing likelihood of unconsciousness",
    (99, 100): "Transformation gas: slowly changes victim into a different form established by the particular alchemical properties of the gas (e.g., lycanthropy gas, giant bug gas, flesh-to-stone gas, etc.) (permanent)"
}

GAS_BEHAVIORS = {
    (1, 10): "Begins as heavier than air (lies near floor) but becomes lighter and rises",
    (11, 20): "Begins as lighter than air (lingers near ceiling) but becomes heavier and sinks",
    (21, 30): "Fills a cubic area, disperses rapidly",
    (31, 40): "Fills a cubic area, lingers",
    (41, 50): "Fills a particular radius, disperses rapidly",
    (51, 60): "Fills a particular radius, lingers",
    (61, 70): "Lies near floor, lingers",
    (71, 80): "Rises near ceiling, lingers",
    (81, 90): "Turns into liquid after a certain duration, and drains away",
    (91, 100): "Turns into solid powder after a certain duration"
}

TRAP_LIQUIDS = {
    (1, 10): "Alchemical",
    (11, 20): "Fast-hardening resin or concrete",
    (21, 30): "Gasoline/kerosene",
    (31, 40): "Greek fire",
    (41, 50): "Oil (non-flammable)",
    (51, 60): "Plaster",
    (61, 70): "Slime",
    (71, 80): "Soup or stew",
    (81, 90): "Viscous/quasi-gel",
    (91, 100): "Water"
}

MISSILE_TRAPS = {
    (1, 5): ("Arrows", "Attached to cable or chain for pulling back"),
    (6, 10): ("Arrows", "Coated in acid"),
    (11, 15): ("Ballista bolt", "Disease carrier"),
    (16, 20): ("Bladed disk or shuriken", "Explosive"),
    (21, 25): ("Bolts", "Poisoned (lethal)"),
    (26, 30): ("Bolts", "Poisoned (non-lethal)"),
    (31, 35): ("Cannonball", "None"),
    (36, 40): ("Darts", "None"),
    (41, 45): ("Darts", "None"),
    (46, 50): ("Grappling hook", "None"),
    (51, 55): ("Grenade", "None"),
    (56, 60): ("Harpoon", "None"),
    (61, 65): ("Lasso", "None"),
    (66, 70): ("Net", "None"),
    (71, 75): ("Shrapnel", "None"),
    (76, 80): ("Sling bullet", "None"),
    (81, 85): ("Sling stone", "None"),
    (86, 90): ("Spear", "None"),
    (91, 95): ("Spiked cannonball", "None"),
    (96, 100): ("Spiked log", "None")
}

PITS = {
    (1, 15): "Normal pit (covered)",
    (16, 20): "Closes and locks",
    (21, 25): "Closes, contains liquid",
    (26, 30): "Closes, locks, floods",
    (31, 35): "Closes, locks, poison spikes at bottom",
    (36, 40): "Closes, locks, sinks down like elevator",
    (41, 45): "Closes, locks, snakes or centipedes inside",
    (46, 50): "Closes, locks, spikes at bottom",
    (51, 55): "Closes, locks, then shifts or rotates to be replaced with new (empty) pit",
    (56, 60): "Closes, locks, walls close to crush",
    (61, 65): "Contains piranha, mutant sea bass, electric eels, etc.",
    (66, 70): "Covered pit, spikes at bottom",
    (71, 75): "Drops to another level of dungeon",
    (76, 80): "Poison spikes at bottom",
    (81, 85): "Uncovered pit",
    (86, 90): "Uncovered pit, ooze or slime at bottom",
    (91, 95): "Uncovered pit, snakes",
    (96, 100): "Uncovered pit, spikes at bottom"
}

POISON_LETHAL = {
    (1, 2): "Adjusted by Constitution score: victim dies in dice roll + Con rounds/hours/days",
    (3, 4): "Adjusted by level: victim dies in dice roll + level rounds/hours/days",
    (5, 6): "Attribute Erosion (lethal): -1 point/minute, death at 0, permanent",
    (7, 8): "Attribute Erosion (lethal): -1 point/minute, death at 0, not permanent",
    (9, 10): "Attribute Erosion (lethal): -1 point/hour, death at 0, permanent",
    (11, 12): "Attribute Erosion (lethal): -1 point/hour, death at 0, not permanent",
    (13, 14): "Damage (lethal quantity): HP damage each hour for days, save or none",
    (15, 16): "Damage (lethal quantity): HP damage each hour for days, success reduces",
    (17, 18): "Damage (lethal quantity): HP damage each hour for days, success means once",
    (19, 20): "Damage (lethal quantity): HP damage each minute for minutes, save or none",
    (21, 22): "Damage (lethal quantity): HP damage each minute for hours, save or none",
    (23, 24): "Damage (lethal quantity): HP damage each minute for minutes, success reduces",
    (25, 26): "Damage (lethal quantity): HP damage each minute for hours, success reduces",
    (27, 28): "Damage (lethal quantity): HP damage each minute for minutes, success once",
    (29, 30): "Damage (lethal quantity): HP damage each minute for hours, success once",
    (31, 32): "Damage (lethal quantity): HP damage each round for rounds, save or none",
    (33, 34): "Damage (lethal quantity): HP damage each round for rounds, success reduces",
    (35, 36): "Damage (lethal quantity): HP damage each round for rounds, success once",
    (37, 38): "Damage (lethal quantity): HP damage each round, forever, save or none",
    (39, 40): "Damage (lethal quantity): HP damage each round, forever, success reduces",
    (41, 42): "Damage (lethal quantity): HP damage each round, forever, success once",
    (43, 44): "Damage from activity: HP damage/hour, physical exertion adds damage",
    (45, 46): "Damage from activity: HP damage/hour, physical exertion saves or instant death",
    (47, 48): "Damage from spell casting: HP damage/hour, casting spells adds damage, unhealable",
    (49, 50): "XP Erosion (lethal): -XP every hour until 0 (death), permanent",
    (51, 52): "XP Erosion (lethal): -XP every hour until 0 (death), returns if neutralized",
    (53, 54): "Internal damage (ability score based): must check Con when taking other damage or die",
    (55, 56): "Internal damage (increasing): 10%+ chance of dying when next taking damage",
    (57, 58): "Internal damage (lethal): 10% chance of dying each time taking damage",
    (59, 60): "Internal damage (progressive): make save when taking damage or die, cumulative -1",
    (61, 62): "Internal damage (saving throw/level based): make save when taking damage or die",
    (63, 64): "Lethal (don't eat): 25% chance of dying every time eating",
    (65, 66): "Lethal (don't eat): will die next time eating food",
    (67, 68): "Lethal (don't sleep): 25% chance of dying whenever sleeping",
    (69, 70): "Lethal (don't sleep): succumb to poison and die when next sleeping",
    (71, 72): "Lethal (stay out of sun): damage from sunlight, unhealable",
    (73, 74): "Lethal, delayed by level: will die in rounds equal to level",
    (75, 76): "Lethal, delayed by level: will die in hours equal to level",
    (77, 78): "Lethal, delayed: death in certain number of combat rounds",
    (79, 80): "Lethal, delayed: death in certain number of hours",
    (81, 82): "Lethal, delayed: death in random number of combat rounds",
    (83, 84): "Lethal, delayed: death in random number of hours",
    (85, 86): "Lethal: Instant death, save avoids completely",
    (87, 88): "Lethal: Instant death, success means damage not death",
    (89, 90): "Level Erosion (lethal): lose level and continue to lose levels until 0 (death), permanent",
    (91, 92): "Level Erosion (lethal): lose level and continue until 0 (death), regained if neutralized",
    (93, 94): "Percentile chance of death (eroding): % chance of dying each hour, increases",
    (95, 96): "Percentile chance of death: % chance of dying instantly each hour",
    (97, 98): "Saving throw checks (eroding): must make save each hour or die, cumulative -1",
    (99, 100): "Saving throw checks: must make save each hour or die"
}

POISON_NON_LETHAL = {
    (1, 10): "Affects ability score(s) (short or long term)",
    (11, 20): "Affects saving throws across the board (short or long term)",
    (21, 30): "Blindness (short or long term)",
    (31, 40): "Catatonia (long or short term)",
    (41, 50): "Confusion (short term)",
    (51, 60): "Deafness (short or long term)",
    (61, 70): "Incapacitated by pain",
    (71, 80): "Paralysis or catatonia (long or short term)",
    (81, 90): "Rage or berserking (short term)",
    (91, 100): "Reduced ability to resist disease (penalty to saving throw) (short or long term)"
}

RIGGED_NATURAL_FEATURES = {
    (1, 5): ("Chasm blocking path", "Something pushes you into it"),
    (6, 10): ("Cliff face or wall requires climbing", "Something collapses you into it"),
    (11, 15): ("Crumbling ceiling or walls", "Something pulls you into it"),
    (16, 20): ("Crumbling floor", "There is a fake 'safe' path that isn't the safe path"),
    (21, 25): ("Dangerous-looking bridge over chasm or river", "Monster in strategic location"),
    (26, 30): ("Force field or other magical barrier", "Mechanical trap in strategic location"),
    (31, 35): ("Geysers of hot water or lava", "Something compels you into it"),
    (36, 40): ("Hot area (volcanic or other)", "Something slides you into it"),
    (41, 45): ("Illusion of another obstacle", "Something lifts you into it"),
    (46, 50): ("Misty area with poor visibility", "Something shakes you into it"),
    (51, 55): ("Pathway side of a cliff", "Something guides you into it"),
    (56, 60): ("Pit blocking path", "Something makes you abnormally reckless"),
    (61, 65): ("Quicksand", "Something reduces your ability to cope with risk"),
    (66, 70): ("River blocks path", "Something reaches out from within it"),
    (71, 75): ("Rivulet crosses path", "Used as a missile-fire ambush"),
    (76, 80): ("Slippery slope", "Device/spell makes it harder to get out"),
    (81, 85): ("Tall ceiling with overhead risks", "Something rotates/shifts to make obstacle more dangerous"),
    (86, 90): ("Thorns/undergrowth/fungus", "Affects balance/senses to prolong exposure"),
    (91, 95): ("Venting steam/gas", "Safe path only works for a few people"),
    (96, 100): ("Wall or fence blocks path", "Another danger herds party into danger zone")
}

MAGICAL_TRAPS = {
    (1, 10): ("Complicated Mechanical Trigger", None, "Magical Effect (Special)"),
    (11, 20): ("Magical Trigger", "Mechanical Effect", "Alignment/Species detector"),
    (21, 30): ("Magical Trigger", "Mechanical Effect", "Beams of light"),
    (31, 40): ("Magical Trigger", "Mechanical Effect", "Carving/Gem can 'see'"),
    (41, 50): ("Magical Trigger", "Magical Effect", "Mist activates when agitated"),
    (51, 60): ("Magical Trigger", "Magical Effect", "Magical speech (password)"),
    (61, 70): ("Magical Trigger", "Magical Effect", "Object 'sends message' when moved"),
    (71, 80): ("Magical Trigger", "Magical Effect", "Presence of intelligence activates"),
    (81, 90): ("Mechanical Trigger (Simple) with Concealment", "Magical Effect", "Presence of life activates"),
    (91, 100): ("Mechanical Trigger (Simple)", "Magical Effect", "Temperature alterations activate")
}

MAGICAL_TRAP_EFFECTS = {
    (1, 10): ("Anti-gravity/levitation", "Alignment-detector, species-detector, or class detector"),
    (11, 20): ("Confuses", "Area is scryed and manually activated"),
    (21, 30): ("Curses", "Beams of light"),
    (31, 40): ("Elemental damage", "Carving/Gem can 'see'"),
    (41, 50): ("Enchants", "Mist activates when agitated"),
    (51, 60): ("Imprisons", "Magical speech (password)"),
    (61, 70): ("Lethal", "Object 'sends message' when moved"),
    (71, 80): ("Paralysis", "Presence of intelligence activates"),
    (81, 90): ("Teleports", "Presence of life activates"),
    (91, 100): ("Transforms", "Temperature alterations activate")
}

MAGICAL_TRAP_TRIGGERS = {
    (1, 10): "Alignment-detector, species-detector, or class detector",
    (11, 20): "Area is scryed and manually activated",
    (21, 30): "Beams of light",
    (31, 40): "Carving, gem, or other feature can 'see' intruders",
    (41, 50): "Clouds or curtains of mist activate when agitated",
    (51, 60): "Magical speech requests password",
    (61, 70): "Object 'sends a message' when picked up/opened",
    (71, 80): "Presence of intelligence activates trap",
    (81, 90): "Presence of life activates trap",
    (91, 100): "Temperature alterations (including body heat) activate trap"
}

MAGICAL_TRAP_CORE_EFFECTS = {
    (1, 10): "Anti-gravity or levitation",
    (11, 20): "Confuses",
    (21, 30): "Curses",
    (31, 40): "Elemental damage",
    (41, 50): "Enchants",
    (51, 60): "Imprisons",
    (61, 70): "Lethal",
    (71, 80): "Paralysis",
    (81, 90): "Teleports",
    (91, 100): "Transforms"
}

MAGICAL_SPECIAL_EFFECTS = {
    (1, 2): "A change in mental processes",
    (3, 4): "A change to the skin",
    (5, 6): "A sphere of elemental substance",
    (7, 8): "A sphere of force or light",
    (9, 10): "Affects internal organs or brain",
    (11, 12): "Can be avoided with certain words",
    (13, 14): "Certain people are unaware of trap functioning",
    (15, 16): "Chiming sound",
    (17, 18): "Darkness, shadows, or intense illumination",
    (19, 20): "Dreams or visions",
    (21, 22): "Fire (oddly colored)",
    (23, 24): "Floating image of person/monster/animal",
    (25, 26): "Floating motes of light",
    (27, 28): "Frost or ice",
    (29, 30): "Glowing metal",
    (31, 32): "Involves a gem",
    (33, 34): "Involves a glass or metal bottle",
    (35, 36): "Involves cloth (tapestry, cloak, carpet)",
    (37, 38): "Involves mirror, lens, window, or ball",
    (39, 40): "Involves mouth making sound",
    (41, 42): "Involves pattern on wall/ceiling",
    (43, 44): "Involves snake or serpentine movement",
    (45, 46): "Involves water source (fountain, pool)",
    (47, 48): "Involves timekeeping device (hourglass, sundial)",
    (49, 50): "Involves disorientation in space",
    (51, 52): "Involves eyes",
    (53, 54): "Involves memory",
    (55, 56): "Involves movement up or down",
    (57, 58): "Involves paper or parchment",
    (59, 60): "Involves pictures on wall/floor",
    (61, 62): "Involves plant matter",
    (63, 64): "Involves runes",
    (65, 66): "Involves time movement",
    (67, 68): "Involves movement of several disks",
    (69, 70): "Involves movement of stone",
    (71, 72): "Involves movement of sand/powder/dirt",
    (73, 74): "Involves sudden appearance of animal",
    (75, 76): "Involves wine",
    (77, 78): "Involves wood",
    (79, 80): "Light beams",
    (81, 82): "Light glow (strangely colored)",
    (83, 84): "Rope, spider webs, tendrils, or tentacles",
    (85, 86): "Sleet or hail",
    (87, 88): "Sparks",
    (89, 90): "Takes effect slowly, avoidable with proper actions",
    (91, 92): "Thorns or needles",
    (93, 94): "Thunderclap",
    (95, 96): "Unwittingly gives clue as side effect",
    (97, 98): "Uses fear",
    (99, 100): "Uses rage or anger"
}

COMPLEX_TRAP_PROFILE = {
    (1, 2): {
        "draw": "Physical or Magical Draw",
        "prison": "Whole party blocked from retreat",
        "kill": "Progressive gas effect",
        "switch": "Mechanical escape hatch",
        "complication": "Monsters or progressive physical immobilization"
    },
    (3, 4): {
        "draw": "Greed (promise of treasure)",
        "prison": "Party physically divided",
        "kill": "Slow-moving mechanical",
        "switch": "Kill-switch or magical escape",
        "complication": "Progressive magically-induced weakness or immobilization"
    },
    (5, 6): {
        "draw": "None",
        "prison": "Some/all of party immobilized",
        "kill": "Repeated mechanical, monster, or magical attacks",
        "switch": "Automatic Timer and Reset",
        "complication": "Backup third-stage kill"
    }
}

TRAP_DRAWS = {
    (1, 10): "Charm or enchanted singing pulls party members",
    (11, 20): "Gravitational or magnetic effect pulls or pushes",
    (21, 30): "Harmless gas or illusionary peril herds party",
    (31, 40): "High wind or vacuum blows party (or vehicle)",
    (41, 50): "Pit opens",
    (51, 60): "Pit opens",
    (61, 70): "Ropes, vines, tentacles, or webs catch and pull",
    (71, 80): "Slide or chute opens",
    (81, 90): "Slide or chute opens",
    (91, 100): "Teleportation or dimensional gateway"
}

TRAP_PRISONS = {
    "blocks_exit": {
        (1, 8): "Chasm, cracks, or gaps in floor open behind party",
        (9, 16): "Wall(s) moves to block exit",
        (17, 24): "Thorns or plants grow or move to block exit",
        (25, 32): "Wall of fire, ice, or wind, or body of water, forms behind party",
        (33, 40): "Snakes, insects, or monster appear behind party to block exit",
        (41, 48): "Bars, grates, or portcullises trap entire party",
        (49, 56): "Party is shifted into a dimensional pocket",
        (57, 65): "Dangerous glyphs form behind party",
        (66, 74): "Force field forms behind party",
        (75, 83): "Frictionless or greased surfaces make escape hard",
        (84, 92): "Party is swallowed by something / Monsters guard exit",
        (93, 100): "Party is turned into gas and sucked through opening"
    },
    "divides_party": {
        (1, 8): "Chasms, cracks, or gaps in floor open",
        (9, 16): "Walls move to divide up the area",
        (17, 24): "Thorns or plants grow in area to divide and entangle",
        (25, 32): "Fire or ice forms to physically divide party (damage possible)",
        (33, 40): "Bars, grates, or portcullises emerge to separate party members",
        (41, 48): "Ropes or chains emerge to separate party members",
        (49, 56): "Time-speeds, other dimensions, or stasis fields separate party",
        (57, 65): "Force fields separate party members (walls, globes, etc.)",
        (66, 74): "Beams or rays of magical power separate party (electrical fence equivalent)",
        (75, 83): "Party members shrink in size and separated by 'great' distances",
        (84, 92): "Powerful monsters push party members into cells then leave",
        (93, 100): "Bars, grates, or portcullises emerge to separate party members"
    },
    "immobilizes": {
        (1, 8): "Entangling (webs, tentacles, ropes, chains, plants, etc.)",
        (9, 16): "Paralyzing",
        (17, 24): "Grabbing (bear traps, magical arms, tentacles, etc.)",
        (25, 32): "Transformation-type attack (stone to flesh beams, etc.)",
        (33, 40): "Adhesives",
        (41, 48): "Cage(s) fall, rise, or form to capture individuals",
        (49, 56): "Pits open to catch individual party members",
        (57, 65): "Ice, glass, Lucite, resin, etc. solidifies to immobilize",
        (66, 74): "Mental inability to move (confusion, rage, fear)",
        (75, 83): "Stasis fields or other dimensions separate/immobilize",
        (84, 92): "Stunning by loud noise, horrid sight, physical blow, etc.",
        (93, 100): "Sleep or magical enchantment"
    }
}

TRAP_KILL_MECHANISMS = {
    "gas": {
        (1, 10): "Periodical unavoidable loss of HP",
        (11, 20): "Periodical unmodified saving throws (until failure)",
        (21, 30): "Declining ability score (death at 0) on failure",
        (31, 40): "Periodical random drops in XP (death at 0)",
        (41, 50): "Periodical unmodified 'attribute checks' (until failure)",
        (51, 60): "Periodical saving throws with cumulative penalty",
        (61, 70): "Loss of HP each time a periodical saving throw fails",
        (71, 80): "Series of flat percentile chances to die or be affected",
        (81, 90): "Series of 'steps' building up inability to act",
        (91, 100): "Periodical loss of HP, random number each time"
    },
    "slow_mechanical": {
        (1, 10): "Closing walls or shrinking enclosure (steamrollers)",
        (11, 20): "Area slowly fills with water or other liquid",
        (21, 30): "Area fills with biting bugs or weak poison gas",
        (31, 40): "Slicing implements move slowly across area",
        (41, 50): "Slowly increasing heat or cold",
        (51, 60): "Air is slowly sucked out of the area",
        (61, 70): "Area fills with deadly poison gas (heavier or lighter than air)",
        (71, 80): "Objects pushed into room until crushed",
        (81, 90): "Countdown shown by hourglass or building threat",
        (91, 100): "Really dangerous monster slowly begins to coalesce"
    },
    "repeated_attacks": {
        (1, 10): "Missile traps fire periodically into area",
        (11, 20): "Rocks or heavy objects fall periodically into area",
        (21, 30): "Monsters are periodically released into area",
        (31, 40): "Swinging arms (wrecking balls) periodically attack",
        (41, 50): "Area-effect spells go off periodically (weak fireballs)",
        (51, 60): "Area-effect spells in parts of area - find safe spot",
        (61, 70): "Walls, ceiling, or floor suddenly contract in certain areas",
        (71, 80): "Dangerous liquids squirt into certain parts of area",
        (81, 90): "Flames, electricity, or frost shoot into random areas",
        (91, 100): "Spears or long spikes stick out into area at random"
    }
}

KILL_SWITCH_WORKING = {
    (1, 25): "Architectural Trick",
    (26, 50): "Unusual Mechanism",
    (51, 75): "Wager Trick",
    (76, 100): "Magical Thing trick"
}

MAGIC_WEAKNESS = {
    (1, 2): "Acid Damage: unable to act/blind/equip damage/normal damage",
    (3, 4): "Adhesiveness and Friction: magical stickiness or slipperiness",
    (5, 6): "Affect Ground/Rock: rock turning to mud or changing while escaping",
    (7, 8): "Affect Metal: animate/magnet/rust/heat/chill/electricity/shape/brittle/constrict",
    (9, 10): "Affect Wood: animate wooden items to attack party",
    (11, 12): "Affect Wood: make brittle or bend wood (race against time)",
    (13, 14): "Affects Use of Limbs: clumpsiness/confusion/cold/twitching",
    (15, 16): "Animate Objects: objects animate and attack party",
    (17, 18): "Asphyxiation: reduces ability to breathe (measured out)",
    (19, 20): "Aversion: magical aversion to something in the trap",
    (21, 22): "Body Infestation: plant or animal growth in victim’s body",
    (23, 24): "Burial: trap keeps trying to bury characters in some substance",
    (25, 26): "Clumsiness: penalty to hit/AC, spell failure, drop items",
    (27, 28): "Cold Damage: increasing cold causes progressive damage",
    (29, 30): "Compelling Sound: magically compel characters to (not) do something",
    (31, 32): "Constitution Loss: slowly drains Con while escaping",
    (33, 34): "Dehydrate/Desiccate: sucks blood or dehydrates into powder",
    (35, 36): "Despondency: intense lethargy, characters won't attempt to escape",
    (37, 38): "Dexterity Loss: slowly drains Dex while escaping",
    (39, 40): "Dimensional Features: taps other dimensions to screw with movement",
    (41, 42): "Disease: fast-acting disease getting progressively worse",
    (43, 44): "Distracting Sound: really distracting sound causing problems",
    (45, 46): "Electrical Damage: progressive electrical damage/loss of coordination",
    (47, 48): "Fear: magical fear, paralyzing or preventing action",
    (49, 50): "Fire: reflex actions (panic/extinguish/writhe) on failing check",
    (51, 52): "Hallucinations or Illusions",
    (53, 54): "Ice: immobilizing/damage/slippery",
    (55, 56): "Immobilization: dancing/twitching/laughing/vomiting/etc.",
    (57, 58): "Implant Eggs or Larva",
    (59, 60): "Insanity: progressive risk of magically induced insanity",
    (61, 62): "Intelligence Loss: slowly drains Intellect while escaping",
    (63, 64): "Light, Dark, and Shadow",
    (65, 66): "Luck: characters become progressively more unlucky",
    (67, 68): "Magic Drain (spells)",
    (69, 70): "Magic Force: pushes or pulls characters",
    (71, 72): "Magical Vortex: powerful whirlwind of poisonous/choking/hot/cold gas",
    (73, 74): "Memory Drain or Wisdom Loss",
    (75, 76): "Movement Inhibitions: binding or entangling",
    (77, 78): "Ongoing Damage: bleeding wounds/racking acid damage",
    (79, 80): "Overload Senses",
    (81, 82): "Paralysis",
    (83, 84): "Progressively Damaging Sound",
    (85, 86): "Rage",
    (87, 88): "Size and Density: size or density being slowly changed",
    (89, 90): "Sleep or Catatonia",
    (91, 92): "Slow",
    (93, 94): "Weakness: induces magical weakness (Str loss possible)",
    (95, 96): "Stun",
    (97, 98): "Telekinesis and Teleportation: items flying/teleporting around",
    (99, 100): "Transformation: slowly being changed into something else"
}

MEASURING_LIFE = {
    (1, 5): "By certain number of combat rounds",
    (6, 10): "By certain number of days",
    (11, 15): "By certain number of hours",
    (16, 20): "By rounds equal to an ability score",
    (21, 25): "By declining points of an ability score",
    (26, 30): "By hit points",
    (31, 35): "By number of character's level",
    (36, 40): "By number of subsequent wounds",
    (41, 45): "By saving throw",
    (46, 50): "By series of saving throws (until failure)",
    (51, 55): "XP decline to 0",
    (56, 60): "Levels decline to 0",
    (61, 65): "Number of times character casts a spell",
    (66, 70): "Number of times character sleeps",
    (71, 75): "Number of times a specific action is performed",
    (76, 80): "Until series of 'attribute checks' finally fails",
    (81, 85): "Until series of 'attribute checks' finally fails (cumulative penalty)",
    (86, 90): "Until series of percentile die rolls fails",
    (91, 95): "Until series of percentile rolls fails (reducing chance/cumulative penalty)",
    (96, 100): "Until series of saving throws fails (cumulative penalty)"
}

def get_from_table(table, roll):
    for (low, high), value in table.items():
        if low <= roll <= high:
            return value
    return "Unknown"

def roll_d100(): return random.randint(1, 100)
def roll_d6(): return random.randint(1, 6)
